apiVersion: v2
name: navlinkswebhook
description: A Helm chart for Admission Webhook to create Navlinks for Prometheus
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
