apiVersion: v2
name: navlinkswebhook
description: A Helm chart for Admission Webhook to create Navlinks for Prometheus
type: application
version: 2.0.1
appVersion: "2.0.1"
maintainers:
- name: eumel8
  email: f.kloeker@telekom.de
  url: https://www.telekom.com
