---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "navlinkswebhook.fullname" . }}
  labels:
    {{- include "navlinkswebhook.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "navlinkswebhook.fullname" . }}
  labels:
    {{- include "navlinkswebhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - "monitoring.coreos.com"
    resources:
    - prometheus
    verbs:
    - get
    - watch
    - list
  - apiGroups:
    - "ui.cattle.io"
    resources:
    - navlinks
    verbs:
    - create
    - delete
    - get
    - list
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "navlinkswebhook.fullname" . }}
  labels:
    {{- include "navlinkswebhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "navlinkswebhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "navlinkswebhook.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
